import React, { useEffect, useState } from 'react'
import axios from 'axios'
import Loading from './Loading'
import { useAppContext } from '../context/AppContext'
import toast from 'react-hot-toast'

const Community = () => {

  const { user, token } = useAppContext()
  const [images, setImages] = useState([])
  const [loading, setLoading] = useState(true)

  const fetchImages = async()=>{
    try {
        const { data } = await axios.get('/api/image/get')
        if (data.success) {
            setImages(data.images)
        }
    } catch (error) {
        console.error("Error fetching images:", error)
    } finally {
        setLoading(false)
    }
  }

  const handleDelete = async (id) => {
    if (!window.confirm("Remove this image from the community showcase?")) return;
    
    try {
      const { data } = await axios.post('/api/image/delete', { id }, { headers: { Authorization: token } });
      if (data.success) {
        toast.success(data.message);
        setImages(prev => prev.filter(img => img._id !== id));
      } else {
        toast.error(data.message);
      }
    } catch (error) {
      toast.error(error.message);
    }
  }

  useEffect(()=>{
    fetchImages()
  },[])

  if(loading) return <Loading />

  return (
    <div className='p-4 pt-10 md:p-8 md:pt-14 xl:px-12 2xl:px-20 w-full mx-auto h-full overflow-y-auto'>
      <h2 className='text-2xl md:text-3xl font-bold mb-8 md:mb-10 text-gray-800 dark:text-white tracking-tight'>
        Community Showcase
      </h2>

      {images.length > 0 ? (
        <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4 gap-6 md:gap-8'>
          {images.map((item, index)=>(
            <div key={index} className='relative group rounded-xl overflow-hidden border border-gray-100 dark:border-white/5 shadow-sm hover:shadow-2xl transition-all duration-700 bg-white dark:bg-white/5'>
              <a href={item.imageUrl} target='_blank' rel="noopener noreferrer" className='block aspect-[4/5] overflow-hidden'>
                <img 
                  src={item.imageUrl} 
                  alt={`Generated by ${item.userName}`} 
                  className='w-full h-full object-cover group-hover:scale-105 transition-transform duration-1000 ease-out'
                />
              </a>

              {/* Delete Button (Creator Only) */}
              {user && user._id === item.userId && (
                <button 
                  onClick={(e) => {
                    e.preventDefault();
                    handleDelete(item._id);
                  }}
                  className='absolute top-2 right-2 p-2 bg-red-500/90 md:bg-red-500/10 md:hover:bg-red-500 backdrop-blur-md rounded-full text-white md:text-red-500 md:hover:text-white transition-all duration-300 z-10 md:opacity-0 md:group-hover:opacity-100'
                  title="Remove from community"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                  </svg>
                </button>
              )}
              
              {/* Attribution Overlay - Desktop: Hover, Mobile: Always Visible (Semi-transparent) */}
              <div className='absolute inset-x-0 bottom-0 p-3 bg-gradient-to-t from-black/80 to-transparent 
                transition-all duration-500 ease-in-out
                md:translate-y-full md:group-hover:translate-y-0
                flex items-center gap-2'>
                
                <div className='w-8 h-8 rounded-full bg-gradient-to-tr from-purple-500 to-indigo-600 flex items-center justify-center text-xs font-bold text-white shadow-xl ring-2 ring-white/10 shrink-0'>
                  {item.userName.charAt(0).toUpperCase()}
                </div>
                
                <div className='flex flex-col min-w-0'>
                  <p className='text-[11px] text-white/50 font-medium uppercase tracking-wider mb-0.5'>Shared by</p>
                  <p className='text-sm font-bold text-white truncate drop-shadow-md'>
                    {item.userName}
                  </p>
                </div>
                
                <div className='ml-auto bg-white/10 backdrop-blur-md p-1.5 rounded-lg opacity-0 md:group-hover:opacity-100 transition-opacity duration-700'>
                  <svg className="w-4 h-4 text-white/70" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                  </svg>
                </div>
              </div>

              {/* Mobile Persistent Indicator Line (Subtle) */}
              <div className='md:hidden absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-purple-500 via-pink-500 to-indigo-500 opacity-70'></div>
            </div>
          ))}
        </div>
      ) : (
        <div className='flex flex-col items-center justify-center py-20 opacity-40'>
          <p className='text-lg font-medium text-gray-500 dark:text-gray-400'>No images shared yet.</p>
        </div>
      )
    }
    </div>
  )
}

export default Community
